apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: babybuddy
  name: babybuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: babybuddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/babybuddy-default: "true"
        io.kompose.service: babybuddy
    spec:
      containers:
        - env:
            - name: CSRF_TRUSTED_ORIGINS
              value: http://127.0.0.1:8000,https://babybuddy.domain.com
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: lscr.io/linuxserver/babybuddy:latest
          name: babybuddy
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: nfs-storage
      restartPolicy: Always
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
status: {}

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: babybuddy
  name: babybuddy
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: babybuddy
  type: LoadBalancer
status:
  loadBalancer: {}