apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: #NFS_SERVER_STORAGESIZE#
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/nfs-share"
    server: #NFS_SERVER_IP#
